- hosts: zabbix_proxies
  become: true
  remote_user: root
  roles:
    - zabbix_proxy2

  vars:
    zabbix_proxy_agent_hostname: "{{ zabbix_proxy_hostname | default(inventory_hostname) }}"
    zabbix_proxy_agent_autoreg_groups:
      - "Linux servers"
      - "Zabbix proxies"
    proxy_auth: ""

  environment:
    http_proxy: "http://{{ proxy_auth ~ '@' if proxy_auth }}proxy.redge.com:3128"
    https_proxy: "http://{{ proxy_auth ~ '@' if proxy_auth }}proxy.redge.com:3128"

  tasks: []
