- hosts: zabbix_proxies
  become: no
  remote_user: root
  roles:
    - zabbix_proxy2
    - role: zabbix_agent3
      vars:
        zabbix_agent_hostname: "{{ zabbix_proxy_hostname | default(inventory_hostname) }}"
        zabbix_agent_autoreg_groups:
          - "Linux servers"
          - "Zabbix proxies"

  vars:
    proxy_auth: ""

  environment:
    http_proxy: "http://{{ proxy_auth ~ '@' if proxy_auth }}proxy.redge.com:3128"
    https_proxy: "http://{{ proxy_auth ~ '@' if proxy_auth }}proxy.redge.com:3128"

  tasks:
    - name: Install and configure Zabbix proxy
      ansible.builtin.import_role:
        name: zabbix_proxy2

    - name: Install and configure Zabbix agent on proxy host
      ansible.builtin.import_role:
        name: zabbix_agent3
      vars:
        zabbix_agent_hostname: "{{ zabbix_proxy_hostname | default(inventory_hostname) }}"
        zabbix_agent_autoreg_groups:
          - "Linux servers"
          - "Zabbix proxies"
